In [1]:
import pickle

In [2]:
with open('./res/res.pkl', 'rb') as f:
    x = pickle.load(f)
    print(x)

[{'img_bbox': {'boxes_3d': CameraInstance3DBoxes(
    tensor([], size=(0, 7))), 'scores_3d': tensor([]), 'labels_3d': tensor([], dtype=torch.int64)}}, {'img_bbox': {'boxes_3d': CameraInstance3DBoxes(
    tensor([[ 3.3751,  2.4014, 35.6786,  4.1879,  1.4866,  1.6930, -1.5299]])), 'scores_3d': tensor([2.6235]), 'labels_3d': tensor([2])}}, {'img_bbox': {'boxes_3d': CameraInstance3DBoxes(
    tensor([[-15.5222,   2.0769,  37.8000,   3.7511,   1.4383,   1.5910,   1.6067]])), 'scores_3d': tensor([1.9315]), 'labels_3d': tensor([2])}}, {'img_bbox': {'boxes_3d': CameraInstance3DBoxes(
    tensor([], size=(0, 7))), 'scores_3d': tensor([]), 'labels_3d': tensor([], dtype=torch.int64)}}, {'img_bbox': {'boxes_3d': CameraInstance3DBoxes(
    tensor([[ -2.3264,   1.1234,  28.7120,   3.4400,   1.5539,   1.5524,  -1.2720],
        [-12.2406,   1.4979,  18.9506,   4.2392,   1.5563,   1.6895,  -0.1149],
        [-11.3166,   1.0667,  34.3010,   3.9833,   1.4036,   1.6034,   1.7767]])), 'scores_3d': tensor(